### ISSUE TITLE
As a user I would like a way to study the states and capitals to learn

### ISSUE THREAD

**Issue by Prometheus66** [cse442-fall-2019-offering/442projects-team-450#67]

**Comment by eykim5** [comment]
Acceptance tests:

- Studying drop down shows 2 pages, one for states, and one for capitals.
- Both states and capitals links move the users to the correct pages.
- The timer and score display should not appear on the states and capital studying pages.
- Each study page should lead to a new gamemode with the US map.
- Clicking on a state will pull up a module that shows the correct state/capital for the respective gamemode.
- Text in the starting module and state modules should be changed so that correspond to the study pages.
